"""create deployment table

Revision ID: 189fdcb98442
Revises: 
Create Date: 2016-02-17 21:13:30.168926

"""

# revision identifiers, used by Alembic.
revision = '189fdcb98442'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('commit', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_last_modified', sa.DateTime(), nullable=False),
    sa.Column('deployed', sa.Boolean(), nullable=True),
    sa.Column('tested', sa.Boolean(), nullable=True),
    sa.Column('msg', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage')
    op.drop_table('deployment')
    ### end Alembic commands ###
